<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Personnel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Account_model');
    } 

    /*
     * Listing of accounts
     */
    function index()
    {
       

        $data['accounts'] = $this->Account_model->get_all_accounts();
        
        $data['_view'] = 'account/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new account
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('JoinDate','JoinDate','exact_length[6]');
		$this->form_validation->set_rules('email','Email','valid_email');
		$this->form_validation->set_rules('UUID','UUID','exact_length[36]');
		$this->form_validation->set_rules('active','Active','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'active' => $this->input->post('active'),
				'DivID' => $this->input->post('DivID'),
				'RankID' => $this->input->post('RankID'),
				'TitleID' => $this->input->post('TitleID'),
				'species' => $this->input->post('species'),
				'gender' => $this->input->post('gender'),
				'Position' => $this->input->post('Position'),
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
				'UUID' => $this->input->post('UUID'),
				'DisplayName' => $this->input->post('DisplayName'),
				'email' => $this->input->post('email'),
				'induction_date' => $this->input->post('induction_date'),
				'dh' => $this->input->post('dh'),
				'JoinDate' => $this->input->post('JoinDate'),
				'DOB' => $this->input->post('DOB'),
				'birth_place' => $this->input->post('birth_place'),
				'height_metric' => $this->input->post('height_metric'),
				'weight_metric' => $this->input->post('weight_metric'),
				'hair_color' => $this->input->post('hair_color'),
				'ethnic_origin' => $this->input->post('ethnic_origin'),
				'nationality' => $this->input->post('nationality'),
				'ident_marks' => $this->input->post('ident_marks'),
				'role' => $this->input->post('role'),
				'cCode' => $this->input->post('cCode'),
				'pfp' => $this->input->post('pfp'),
				'last_login' => $this->input->post('last_login'),
            );
            
            $account_id = $this->Account_model->add_account($params);
            redirect('personnel/index');
        }
        else
        {
			$this->load->model('Division_model');
			$data['all_divisions'] = $this->Division_model->get_all_divisions();

			$this->load->model('Rank_model');
			$data['all_rank'] = $this->Rank_model->get_all_rank();

			$this->load->model('Title_model');
			$data['all_titles'] = $this->Title_model->get_all_titles();

			$this->load->model('Species_model');
			$data['all_species'] = $this->Species_model->get_all_species();

			$this->load->model('Ship_model');
			$data['all_ships'] = $this->Ship_model->get_all_ships();
            
            $data['_view'] = 'account/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a account
     */
    function edit($ID)
    {   
        // check if the account exists before trying to edit it
        $data['account'] = $this->Account_model->get_account($ID);
        
        if(isset($data['account']['ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('JoinDate','JoinDate','exact_length[6]');
			$this->form_validation->set_rules('email','Email','valid_email');
			$this->form_validation->set_rules('UUID','UUID','exact_length[36]');
			$this->form_validation->set_rules('active','Active','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'active' => $this->input->post('active'),
					'DivID' => $this->input->post('DivID'),
					'RankID' => $this->input->post('RankID'),
					'TitleID' => $this->input->post('TitleID'),
					'species' => $this->input->post('species'),
					'gender' => $this->input->post('gender'),
					'Position' => $this->input->post('Position'),
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
					'UUID' => $this->input->post('UUID'),
					'DisplayName' => $this->input->post('DisplayName'),
					'email' => $this->input->post('email'),
					'induction_date' => $this->input->post('induction_date'),
					'dh' => $this->input->post('dh'),
					'JoinDate' => $this->input->post('JoinDate'),
					'DOB' => $this->input->post('DOB'),
					'birth_place' => $this->input->post('birth_place'),
					'height_metric' => $this->input->post('height_metric'),
					'weight_metric' => $this->input->post('weight_metric'),
					'hair_color' => $this->input->post('hair_color'),
					'ethnic_origin' => $this->input->post('ethnic_origin'),
					'nationality' => $this->input->post('nationality'),
					'ident_marks' => $this->input->post('ident_marks'),
					'role' => $this->input->post('role'),
					'cCode' => $this->input->post('cCode'),
					'pfp' => $this->input->post('pfp'),
					'last_login' => $this->input->post('last_login'),
                );

                $this->Account_model->update_account($ID,$params);            
                redirect('personnel/index');
            }
            else
            {
				$this->load->model('Division_model');
				$data['all_divisions'] = $this->Division_model->get_all_divisions();

				$this->load->model('Rank_model');
				$data['all_rank'] = $this->Rank_model->get_all_rank();

				$this->load->model('Title_model');
				$data['all_titles'] = $this->Title_model->get_all_titles();

				$this->load->model('Species_model');
				$data['all_species'] = $this->Species_model->get_all_species();

				$this->load->model('Ship_model');
				$data['all_ships'] = $this->Ship_model->get_all_ships();

                $data['_view'] = 'account/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The account you are trying to edit does not exist.');
    } 

    /*
     * Deleting account
     */
    function remove($ID)
    {
        $account = $this->Account_model->get_account($ID);

        // check if the account exists before trying to delete it
        if(isset($account['ID']))
        {
            $this->Account_model->delete_account($ID);
            redirect('personnel/index');
        }
        else
            show_error('The account you are trying to delete does not exist.');
    }
    
}
