<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get account by ID
     */
    function get_account($ID)
    {
        return $this->db->get_where('accounts',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all accounts count
     */
    function get_all_accounts_count()
    {
        $this->db->from('accounts');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all accounts
     */
    function get_all_accounts($params = array())
    {
        $this->db->order_by('ID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('accounts')->result_array();
    }
        
    /*
     * function to add new account
     */
    function add_account($params)
    {
        $this->db->insert('accounts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update account
     */
    function update_account($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('accounts',$params);
    }
    
    /*
     * function to delete account
     */
    function delete_account($ID)
    {
        return $this->db->delete('accounts',array('ID'=>$ID));
    }
}
