<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Building_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get building by BuildingID
     */
    function get_building($BuildingID)
    {
        return $this->db->get_where('buildings',array('BuildingID'=>$BuildingID))->row_array();
    }
        
    /*
     * Get all buildings
     */
    function get_all_buildings()
    {
        $this->db->order_by('BuildingID', 'desc');
        return $this->db->get('buildings')->result_array();
    }
        
    /*
     * function to add new building
     */
    function add_building($params)
    {
        $this->db->insert('buildings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update building
     */
    function update_building($BuildingID,$params)
    {
        $this->db->where('BuildingID',$BuildingID);
        return $this->db->update('buildings',$params);
    }
    
    /*
     * function to delete building
     */
    function delete_building($BuildingID)
    {
        return $this->db->delete('buildings',array('BuildingID'=>$BuildingID));
    }
}
