<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comm_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comm by comid
     */
    function get_comm($comid)
    {
        return $this->db->get_where('comms',array('comid'=>$comid))->row_array();
    }
        
    /*
     * Get all comms
     */
    function get_all_comms()
    {
        $this->db->order_by('comid', 'desc');
        return $this->db->get('comms')->result_array();
    }
        
    /*
     * function to add new comm
     */
    function add_comm($params)
    {
        $this->db->insert('comms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comm
     */
    function update_comm($comid,$params)
    {
        $this->db->where('comid',$comid);
        return $this->db->update('comms',$params);
    }
    
    /*
     * function to delete comm
     */
    function delete_comm($comid)
    {
        return $this->db->delete('comms',array('comid'=>$comid));
    }
}
