<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Division_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get division by did
     */
    function get_division($did)
    {
        return $this->db->get_where('divisions',array('did'=>$did))->row_array();
    }
        
    /*
     * Get all divisions
     */
    function get_all_divisions()
    {
        $this->db->order_by('did', 'desc');
        return $this->db->get('divisions')->result_array();
    }
        
    /*
     * function to add new division
     */
    function add_division($params)
    {
        $this->db->insert('divisions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update division
     */
    function update_division($did,$params)
    {
        $this->db->where('did',$did);
        return $this->db->update('divisions',$params);
    }
    
    /*
     * function to delete division
     */
    function delete_division($did)
    {
        return $this->db->delete('divisions',array('did'=>$did));
    }
}
