<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Offices_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get directory by LocationID
     */
    function get_directory($LocationID)
    {
        return $this->db->get_where('directory',array('LocationID'=>$LocationID))->row_array();
    }
        
    /*
     * Get all directory
     */
    function get_all_directory()
    {
        $this->db->order_by('LocationID', 'desc');
        return $this->db->get('directory')->result_array();
    }
        
    /*
     * function to add new directory
     */
    function add_directory($params)
    {
        $this->db->insert('directory',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update directory
     */
    function update_directory($LocationID,$params)
    {
        $this->db->where('LocationID',$LocationID);
        return $this->db->update('directory',$params);
    }
    
    /*
     * function to delete directory
     */
    function delete_directory($LocationID)
    {
        return $this->db->delete('directory',array('LocationID'=>$LocationID));
    }
}
