<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Property_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get property by 
     */
    function get_property($)
    {
        return $this->db->get_where('properties',array(''=>$))->row_array();
    }
        
    /*
     * Get all properties
     */
    function get_all_properties()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('properties')->result_array();
    }
        
    /*
     * function to add new property
     */
    function add_property($params)
    {
        $this->db->insert('properties',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update property
     */
    function update_property($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('properties',$params);
    }
    
    /*
     * function to delete property
     */
    function delete_property($)
    {
        return $this->db->delete('properties',array(''=>$));
    }
}
