<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rank_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rank by RankID
     */
    function get_rank($RankID)
    {
        return $this->db->get_where('rank',array('RankID'=>$RankID))->row_array();
    }
        
    /*
     * Get all rank
     */
    function get_all_rank()
    {
        $this->db->order_by('RankID', 'desc');
        return $this->db->get('rank')->result_array();
    }
        
    /*
     * function to add new rank
     */
    function add_rank($params)
    {
        $this->db->insert('rank',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rank
     */
    function update_rank($RankID,$params)
    {
        $this->db->where('RankID',$RankID);
        return $this->db->update('rank',$params);
    }
    
    /*
     * function to delete rank
     */
    function delete_rank($RankID)
    {
        return $this->db->delete('rank',array('RankID'=>$RankID));
    }
}
