<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ship_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ship by registry_id
     */
    function get_ship($registry_id)
    {
        return $this->db->get_where('ships',array('registry_id'=>$registry_id))->row_array();
    }
        
    /*
     * Get all ships
     */
    function get_all_ships()
    {
        $this->db->order_by('registry_id', 'desc');
        return $this->db->get('ships')->result_array();
    }
        
    /*
     * function to add new ship
     */
    function add_ship($params)
    {
        $this->db->insert('ships',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ship
     */
    function update_ship($registry_id,$params)
    {
        $this->db->where('registry_id',$registry_id);
        return $this->db->update('ships',$params);
    }
    
    /*
     * function to delete ship
     */
    function delete_ship($registry_id)
    {
        return $this->db->delete('ships',array('registry_id'=>$registry_id));
    }
}
