<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Species_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get species by species_id
     */
    function get_species($species_id)
    {
        return $this->db->get_where('species',array('species_id'=>$species_id))->row_array();
    }
        
    /*
     * Get all species
     */
    function get_all_species()
    {
        $this->db->order_by('species_id', 'desc');
        return $this->db->get('species')->result_array();
    }
        
    /*
     * function to add new species
     */
    function add_species($params)
    {
        $this->db->insert('species',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update species
     */
    function update_species($species_id,$params)
    {
        $this->db->where('species_id',$species_id);
        return $this->db->update('species',$params);
    }
    
    /*
     * function to delete species
     */
    function delete_species($species_id)
    {
        return $this->db->delete('species',array('species_id'=>$species_id));
    }
}
