<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Time_clock_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get time_clock by id
     */
    function get_time_clock($id)
    {
        return $this->db->get_where('time_clock',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all time_clock
     */
    function get_all_time_clock()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('time_clock')->result_array();
    }
        
    /*
     * function to add new time_clock
     */
    function add_time_clock($params)
    {
        $this->db->insert('time_clock',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update time_clock
     */
    function update_time_clock($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('time_clock',$params);
    }
    
    /*
     * function to delete time_clock
     */
    function delete_time_clock($id)
    {
        return $this->db->delete('time_clock',array('id'=>$id));
    }
}
