<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Title_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get title by tid
     */
    function get_title($tid)
    {
        return $this->db->get_where('titles',array('tid'=>$tid))->row_array();
    }
        
    /*
     * Get all titles
     */
    function get_all_titles()
    {
        $this->db->order_by('tid', 'desc');
        return $this->db->get('titles')->result_array();
    }
        
    /*
     * function to add new title
     */
    function add_title($params)
    {
        $this->db->insert('titles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update title
     */
    function update_title($tid,$params)
    {
        $this->db->where('tid',$tid);
        return $this->db->update('titles',$params);
    }
    
    /*
     * function to delete title
     */
    function delete_title($tid)
    {
        return $this->db->delete('titles',array('tid'=>$tid));
    }
}
