<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Version_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get version by vid
     */
    function get_version($vid)
    {
        return $this->db->get_where('versions',array('vid'=>$vid))->row_array();
    }
        
    /*
     * Get all versions
     */
    function get_all_versions()
    {
        $this->db->order_by('vid', 'desc');
        return $this->db->get('versions')->result_array();
    }
        
    /*
     * function to add new version
     */
    function add_version($params)
    {
        $this->db->insert('versions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update version
     */
    function update_version($vid,$params)
    {
        $this->db->where('vid',$vid);
        return $this->db->update('versions',$params);
    }
    
    /*
     * function to delete version
     */
    function delete_version($vid)
    {
        return $this->db->delete('versions',array('vid'=>$vid));
    }
}
